n0-computer/quinn

iroh-quinn/src/connection.rs

Since this is a weak reference inside it is useful to know if the
handle is still useable.

feat: Add liveness for WeakConnectionHandle

---

quinn-udp/src/cmsg.rs
quinn-udp/src/lib.rs
quinn-udp/src/unix.rs
quinn/src/tests.rs

- compiles & passes tests on FreeBSD
- compiles & passes tests on NetBSD
- compiles & passes tests on OpenBSD

fix NetBsd and FreeBsd

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/paths.rs
quinn/src/connection.rs
quinn/src/lib.rs

This gives access to a low-level handle for a connection which allows resetting of the congestion controller state.  This is helpful when there is out-of-band knowledge about changes to the underlying network path.

Allow resetting of the congestion controller

---

.github/workflows/rust-android-run-tests-on-emulator.sh
.github/workflows/rust.yml
quinn-proto/Cargo.toml
quinn-proto/src/config.rs
quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/stats.rs
quinn-proto/src/crypto/rustls.rs
quinn-proto/src/endpoint.rs
quinn-proto/src/tests/mod.rs
quinn-proto/src/tests/util.rs
quinn-udp/Cargo.toml
quinn-udp/src/cmsg/mod.rs
quinn-udp/src/lib.rs
quinn-udp/src/unix.rs
quinn-udp/tests/tests.rs
quinn/Cargo.toml
quinn/src/tests.rs

This merges all the commits in the last release, i.e. the `main` branch up to the `quinn-udp-0.5.5` tag.
It adds one extra fix to CI to also run on pushes to the 0.11.x branch.  This was missed in the earlier creation of the 0.11.x branch.

Merge latest release into 0.11.x

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/mtud.rs
quinn-proto/src/connection/paths.rs
quinn/src/connection.rs

The existing mechanism to reset the congestion controller and RTT estimator is insufficient: the MTU should also start anew when the path has changed.  This adds this to the same method and renames the functions to make their use clearer.

Also reset the MTU when the network paths has changed

---

quinn-proto/src/address_discovery.rs
quinn-proto/src/config.rs
quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/paths.rs
quinn-proto/src/connection/spaces.rs
quinn-proto/src/connection/stats.rs
quinn-proto/src/frame.rs
quinn-proto/src/lib.rs
quinn-proto/src/tests/mod.rs
quinn-proto/src/transport_parameters.rs
quinn-proto/src/varint.rs
quinn/Cargo.toml
quinn/examples/client.rs
quinn/examples/server.rs
quinn/src/connection.rs

PoC for an address discovery extension implementation on quinn.
1. Transport parameters: These are how the extension is negotiated between peers. Implemented with tests, can't be changed in 0rtt
2. Frames: Where we actually send the data. Technically two different kind of frames, one for ipv4 and other for ipv6. This is implemented as a single struct with tests.
3. Frame sending, aka "the logic":
- we store whether a path has reported the observed address to ensure the first path receives an observation.
- we send with path challenges since those ensure we send the frame when we identify a change in the peer's address. If my understanding is correct this also covers probing.
- we send with path responses too. This is not required by the spec but technically allowed. I'm fine to remove it …

QUIC Address discovery extension

---

README.md

Listing the actual versions seems like it might be out of date quickly.  So I added how to find out instead.

Describe how to find the upstream version

---

quinn-proto/src/endpoint.rs
quinn-proto/src/transport_parameters.rs

This addresses 3 ToDos that don't actually change the code:
1. what path should be used to attempt to remove packet protection when receiving the first packet?
None. The extension has not been successfully negotiated
2. what path should be used for packet protection of an initial close?
None. Initial close is done before the handshake is completed and the extension has not been negotiated.
3. 0-rtt multipath validations:
None: Section 7 of rfc9000 states that extensions must declare what happens with 0-rtt transport parameters and the draft states that `initial_max_path_id` must not be remembered. This is (to me) equivalent to silently ignoring any 0-rtt params as what comes from finalizing the handshake is used
All of this needs some review from someone else

Address ToDo about packet protection and 0rtt validation

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/spaces.rs

This is a bit sad because it splits the use in poll_transmit.  It will
need more adjustments once poll_transmit starts sending on multiple
paths though.

Kind of do tail-loss probes correctly

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/spaces.rs
quinn-proto/src/tests/mod.rs

This moves the immediate-ack state to the path, I think this is multipath-compatible as much as normal acks are.

ack-frequencies is allowed together with multipath

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/paths.rs
quinn-proto/src/connection/spaces.rs

WIP
If there's an active path we only want to send packets that must be sent on a backup path on the backup path.  All the other packets should go on the active path, even if the active path is congestion blocked.

Send most of the stuff only on active paths

---

quinn-proto/src/config/transport.rs
quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/paths.rs
quinn-proto/src/transport_parameters.rs

as stated in title. This is necessary to start the process of opening a new path

keep track of the local and remote max path id

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/timer.rs

`Timer::PushNewCid` is never stopped so it doesn't need to be guarded against incidental stops. Doing this in a loop is more efficient than rearming constantly because we know there _will_ be push new cid timers that share the same expiry: from "proactively issuing new CIDs" when the connection is established and multipath is negotiated
I had already added some tests for this and the test keeps working fine

simplify Timer::PushNewCid logic

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/stats.rs
quinn-proto/src/tests/mod.rs
quinn-proto/src/transport_parameters.rs

As part of this a few minor fixes, in recording and logging the PATH_NEW_CONNECTION_ID frames.
Also a few fixes for logging frames that were mistakenly not logged.

This adds a frame stat for PATH_NEW_CONNECTION_ID

---

quinn/Cargo.toml

According to the 0.13 tag, the last release was a8cca03, the diff is only in the quinn crate:
```
$ git diff a8cca03 --stat
.github/workflows/rust.yml    |   6 +--
quinn/Cargo.toml              |   2 +-
quinn/src/connection.rs       |  51 +++++++------------
quinn/src/endpoint.rs         |  76 +++++++++++++++++-----------
quinn/src/lib.rs              |   9 ++--
quinn/src/runtime.rs          | 202 +++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
quinn/src/runtime/async_io.rs |  46 ++++++++---------
quinn/src/runtime/tokio.rs    |  41 +++++++++-------
8 files changed, 260 insertions(+), 173 deletions(-)
```

chore(quinn): Prepare `iroh-quinn` for the 0.14 release

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/paths.rs
quinn-proto/src/connection/spaces.rs
quinn-proto/src/connection/stats.rs
quinn-proto/src/frame.rs
quinn-proto/src/lib.rs
quinn-proto/src/tests/multipath.rs
quinn/src/path.rs

This always accepts the status set by the peer, the draft says it is only a suggestion.

send and receive PATH_AVAILABLE/PATH_BACKUP

---

quinn-proto/src/config/transport.rs
quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/packet_builder.rs
quinn-proto/src/connection/paths.rs
quinn-proto/src/connection/timer.rs
quinn-proto/src/tests/mod.rs
quinn/src/path.rs

The following might perhaps better flow over to another PR

Per-path idle timeout and keepalive

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/packet_builder.rs

Adds the path id to the send and recv spans to help with debugging. Probably useful for everyone so adding this change early

Add path id to spans to help with debugging

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/paths.rs
quinn-proto/src/connection/spaces.rs

- changes the `PathStatusState` to fully contain status updates, both local and remote
- change the scheduling of path status frames to be sent only after the challenge is sent. Note that this is probably not enough, just better than the current state. This is not enough because the application can (in theory, even if unlikely) change the status before the path is really open and this bypasses the initial scheduling
- changes the pending paths to ensure only the last status is sent
- registers the sent frame with retransmits

fix some path status bugs, improve path status story

---

quinn-proto/src/connection/mod.rs

No need to remove duplicates with a set or iterate when one these is already sorted

simplify getting the next path id

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/timer.rs
quinn-proto/src/tests/multipath.rs
quinn-proto/src/tests/util.rs

This PR continues work around opening a path:
- check if the remote is known to consider a path validated on both client and server sides
- still send the PATH_CHALLENGE. The reason for this is keeping some logic simple: emitting the event that declares to the application that the path is open is supposed to be "usable" more than open, for this we need the path to be open and validated. Simply sending the PATH_CHALLENGE ensures the path is opened in any case by guaranteeing something is sent on the path and something is received in return (the PATH_RESPONSE). This is a single frame that ids in this, while still keeping the path as validated and immediately usable if the remote is known
- sets validation timers for opening a path. For this I chose a different timer because the current one …

handle some edge cases in opening a path

---

quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/timer.rs

- improve comment to distinguish migrations only as RFC9000 and multipath's path creation
- actually stop timer when frames are received
- set the open path timer when the path is created in the internal state, not when the frame is sent

fix open path timer issues

---

deny.toml
quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/streams/mod.rs
quinn/src/mutex.rs

To support sending initial packets to many destinations and accepting
the first one received back, we need to allow the server address to
migrate.
Once we have validated the server's address during the handshake we
no longer allow the server's address to migrate.
This also adds the logic to consider the server's address validated in
a retry packet if possible.

allow server migrations

---

Cargo.lock
quinn-proto/src/connection/mod.rs
quinn-proto/src/connection/paths.rs
quinn-proto/src/tests/mod.rs
quinn-proto/src/tests/multipath.rs
quinn-proto/src/tests/util.rs
quinn/Cargo.toml
quinn/src/connection.rs
quinn/src/path.rs
quinn/src/tests.rs

Some changes that are relevant in this PR:
- protocol wise changes are minimal since it was clear from the beginning that observed addresses were meant to be kept by path. 
- We _still_ send observed address reports with path challenges and responses. This was originally intended but now results on double reports when opening a path. This seems fine to me for now since helps reports to remain updated. We could evaluate removing this
- we keep track of whether the path has been informed as open to the application to emit the relevant events afterwards. We should probably use this for status as well if we continue with emitting the event when the path is in fact open (a packet has been successfully received)
- Address updates can be obtained via the `Path` api
- I noticed we might be …

add public api for observed address with multipath

---

quinn/src/connection.rs
quinn/src/path.rs

The introduction of the watcher into the `OpenPathInner` broke the upwards wake, making the future that handles dealing with the state changes not being polled. Because of this tests that use the `open_path` api take several seconds, until the runtime decides by chance to poll the future. By changing this to store a stream (an actual future, until a watcher, the futures are now polled in a timelly matter. The test for address discovery for examples used to take 30.22seconds, now it's 0.22 seconds
This also simplifies the code by watching for changes instead of values, which removes the need to deal with `None`s that will never happen

Fix open path api
